services:
  - type: web
    name: gold-price-predictor
    runtime: python
    repo: https://github.com/Soham8788/gold-price-predictor
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: gunicorn app:app